### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by wulucxy** [eventbrite/britecharts-react#122] opened 2018-02-26 07:38 UTC
Failed to compile.

./src/charts/helpers/validation.js

/work/d3/britecharts-react-master/src/charts/helpers/validation.js
  24:30  warning  'data' is defined but never used  no-unused-vars

✖ 1 problem (0 errors, 1 warning)

 @ ./src/charts/bar/barChart.js 13:18-50
 @ ./src/charts/bar/Bar.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/charts/bar/Bar.js

**Comment by miglesiasEB** [comment] 2018-03-01 00:49
This warning should be fixed with the last PR.
Closing now.

**Comment by wulucxy** [comment] 2018-03-06 07:53
@miglesiasEB still does not work。
the error message is:
```
VM4969 87:97 Uncaught TypeError: Cannot read property 'PureComponent' of undefined
    at eval (VM4969 87:97)
    at Object.<anonymous> (Step.js:1103)
    at __webpack_require__ (Step.js:20)
    at eval (Step.js:4)
    at Object.<anonymous> (Step.js:1160)
    at __webpack_require__ (Step.js:20)
    at Object.<anonymous> (Step.js:1147)
    at __webpack_require__ (Step.js:20)
    at Step.js:63
    at Step.js:66
```

**Comment by miglesiasEB** [comment] 2018-03-06 16:04
Will try to reproduce, thanks!

**Comment by wulucxy** [comment] 2018-03-09 09:18
@maberastain-eb can you tell me how to start this project? 
`npm run start` can not work

**Comment by Golodhros** [comment] 2018-03-10 03:41
Hi @wulucxy, could you update master and try again?
I cannot reproduce the error. Which node version are you using?

**Comment by wulucxy** [comment] 2018-03-10 14:08
my node is `v7.10.1`。
and i use yarn for installation.

**Comment by Golodhros** [comment] 2018-03-10 19:02
Hi @wulucxy,

Using yarn to install in 7.10 showed this message:
```warning You are using Node "7.10.1" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"```
Maybe that's the issue?

When using npm to install and to run start with your node version it worked fine

**Comment by wulucxy** [comment] 2018-03-14 07:10
error msg:
<img width="697" alt="_65e1ade7-fd2b-407c-9b05-6693408b413c" src="https://user-images.githubusercontent.com/5326403/37387983-9cd60d98-2799-11e8-966c-093478df0f8b.png">

```
node -v
v7.10.1
```
dashborad
<img width="875" alt="_dd4429cc-b75a-4051-b733-650ceef7a19a" src="https://user-images.githubusercontent.com/5326403/37388022-c13abe4a-2799-11e8-9c2c-47003840e8e7.png">

**Comment by wulucxy** [comment] 2018-03-14 07:11
@Golodhros `npm run build` seems ok。

so, how do you run the dev server?

**Comment by Golodhros** [comment] 2018-03-14 16:19
Did you try to install everything with npm instead of yarn?

For running the dev server you need to run that 'npm run start' and do also 'npm run styleguide' in order to see the docs.

**Comment by Golodhros** [comment] 2018-04-01 23:25
Hi, could you make this work @wulucxy ?

**Closed** 2018-12-04 19:21 UTC
Labels: question
